blank_issues_enabled: true
contact_links:
  - name: 版本库Telegram频道
    url: https://t.me/spectrollay_minecraft_repository
    about: 版本库消息推送以及聊天,建议和反馈途径
  - name: 版本库QQ频道
    url: https://pd.qq.com/s/h8a7gt2u4
    about: 版本库消息推送以及聊天,建议和反馈途径
  - name: 我的Telegram群组
    url: https://t.me/Spectrollay_MCW
    about: 个人项目聊天群(此处不接受建议和反馈)
  - name: 我的QQ群组
    url: https://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=WVA6aPqtv99hiYleW7vUq5OsBIufCAB1&authKey=B0%2BaXMCTqnmQrGh0wzCZTyWTIPyHS%2FPEM5QXcFfVwroFowNnzs6Yg1er1%2F8Fekqp&noverify=0&group_code=833473609
    about: 个人项目聊天群(此处不接受建议和反馈)
  - name: 我的云湖群组
    url: https://yhfx.jwznb.com/share?key=VyTE7W7sLwRl&ts=1684642802
    about: 个人项目聊天群(此处不接受建议和反馈)